server:
  servlet:
    context-path: /ruready-api
  port: 8000

logging:
  level:
    liquibase: INFO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ruready
    username: ruready
    password: ruready
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        default_schema: public
    open-in-view: true
